export const MEDIA = {
  videos: {
    hero: '/videos/Technician_inspecting_heating_system.mp4',
    gas: '/videos/Gas Installation.mp4',
    heating: '/videos/Technician_inspecting_residential_heating_adjustment.mp4',
    water: '/videos/Plumber_installing_modern_water.mp4',
    bathroom: '/videos/bathroom-reveal.mp4',
    craftsmanship: '/videos/craftsmanship-hands.mp4',
    vienna: '/videos/vienna-establishing.mp4',
    technicianCustomer: '/videos/technician-customer.mp4',
  },
  posters: {
    hero: '/images/hero-poster.jpg',
    heating: '/images/heating-poster.jpg',
    water: '/images/water-poster.jpg',
    bathroom: '/images/bathroom-poster.jpg',
    craftsmanship: '/images/craftsmanship-poster.jpg',
    vienna: '/images/vienna-poster.jpg',
    technicianCustomer: '/images/technician-customer-poster.jpg',
  },
  images: {
    heroAlternative: '/images/hero-apartment.jpg',
    gas: '/images/Gas installation.png',
    water: '/images/Water Installation.png',
    heating: '/images/Heating Systems.jpg',
    bathroom: '/images/Sanitary.jpg',
    company: '/images/company-portrait.jpg',
    team: '/images/team-photo.jpg',
    vienna: '/images/vienna-exterior.jpg',
    office: '/images/rudolf-office.jpg',
    tools: '/images/tools-detail.jpg',
    pipes: '/images/pipe-detail.jpg',
    generational: '/images/generational-home.jpg',
  },
} as const
